/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.Form;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import Client.GUIClientMain;
/**
 *
 * @author aless
 */
@SuppressWarnings("serial")
public class Cards extends javax.swing.JFrame {

	private static final String WORTH_ICON = "img/worth_icon.png";
	private String name;
	private Integer where; //in quale lista siamo (TODO ETC)
	private String[] data;
	private Integer Selected = -1;
    /**
     * Creates new form Card
     */
    public Cards(String name, Integer choosen) {
    	this.name = name;
    	this.where = choosen;
        initComponents();
        ImageConfig();
    }

	 public void ImageConfig() {
	     ImageIcon imgIcon = new ImageIcon(WORTH_ICON);
	     this.setIconImage(imgIcon.getImage());
	 }
 
	 public String NameList() {
		String [] name = {"TO DO", "IN PROGRESS","TO BE REVISED", "DONE"};
			
		return name[this.where];
	 }
	 
	 public int ReturnIndex(String value) {
		 String [] name = {"TO DO", "IN PROGRESS","TO BE REVISED", "DONE"};
		 
		 for(int i = 0; i<name.length; i++) {
			 if(name[i].equals(value))
				 return i;
		 }
		return -1;
	 }
	 
	 public void ComboList() {
		 switch(where) {
		 	case 0:
		 		ComboCards.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN PROGRESS" }));
		 		break;
		 	case 1:
		 		ComboCards.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TO BE REVISED", "DONE"}));
		 		break;
		 	case 2:
		 		ComboCards.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN PROGRESS" }));
		 		break;
		 	case 3:
		 		ComboCards.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
		 		break;
		 }
	 }
	 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
	 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        String cards = GUIClientMain.GetCards(this.name, this.where);
        
        String endline = GUIClientMain.RerturnEnd();

	    this.data = cards.split(endline); // Name
        
    	this.setTitle(name + " - Show card");
    	this.setVisible(true);
    	this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    	this.setResizable(false);
    	this.setLocationRelativeTo(null);
    	
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboCards = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        LabelGroupCard = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        
        jLabel1.setText("Selected:");

        jLabel2.setText("Move to:");

        jLabel3.setText("");

        ComboList();

        jButton1.setText("Move");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	MoveActionPerformed(evt);
            }
        });

        LabelGroupCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelGroupCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelGroupCard.setText(NameList());
        LabelGroupCard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	BackActionActionPerformed(evt);
            }
        });

        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ShowCardActionPerformed(evt);
            }
        });
        
        DefaultListModel<String> model = new DefaultListModel<String>();

        for(int i = 0; i < data.length ; ++i){
        	model.addElement(data[i]);
        }
        
        if(!cards.equals("NOTFOUND"))
        	jList1.setModel(model);
        
        jList1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                Selected = jList1.getSelectedIndex();
                jLabel3.setText(data[Selected]);
            }
        });
        
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelGroupCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelGroupCard)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComboCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowCardActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	GUIClientMain.ShowCard(this.name, data[Selected], this.where);
    }

    private void BackActionActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	GUIClientMain.ProjectCard(this.name);
    }
    
    private void MoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	String value = ComboCards.getSelectedItem().toString();
    	
    	int chosen = ReturnIndex(value);
    	if(Selected >= 0) {
	    	if(chosen >= 0 && GUIClientMain.MoveCards(this.name, data[Selected], this.where, chosen)) {
	    		GUIClientMain.ShowCards(this.name, this.where);
	    	}
	    	else {
	    		JOptionPane.showMessageDialog(this, "Something went wrong");
	    		GUIClientMain.ShowCards(this.name, this.where);
	    	}
    	}
    	else {
    		JOptionPane.showMessageDialog(this, "Select a row first");
    	}
    }

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCards;
    private javax.swing.JLabel LabelGroupCard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
