/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.Form;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import Client.GUIClientMain;

/**
 *
 * @author aless
 */
public class ProjectCard extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6204181202565453536L;
	private static final String WORTH_ICON = "img/worth_icon.png";
	private String name;
	
    /**
     * Creates new form ProjectCard
     */
    public ProjectCard(String name) {
    	this.name = name;
	    String data = GetProject();
	     
    	ImageConfig();
        initComponents();
        Setting(data);
    }

	 public void ImageConfig() {
	     ImageIcon imgIcon = new ImageIcon(WORTH_ICON);
	     this.setIconImage(imgIcon.getImage());
	 }
 
	 public String GetProject() {
		 return GUIClientMain.ShowPrj(this.name);
	 }
	 
	 public void Setting(String data) {
		 String adder = GUIClientMain.ReturnAdder();
	        
	     String[] prj = data.split(adder); // Name, Owner, Deadline, Description , DataCreated
	     
	     if(!data.equals("NOTFOUND")) {
		     DeadlineField1.setText(prj[2]);
		     
		     DescriptionArea.setText(prj[3]);
		     
		     NameProject.setText(prj[0]);
		     
		     OwnerField.setText(prj[1]);
		     
		     DeadlineField.setEditable(false);
		     DeadlineField.setBackground(new java.awt.Color(255, 255, 255));
		     DeadlineField.setText(prj[2]);
	
		     DeadlineField2.setEditable(false);
		     DeadlineField2.setBackground(new java.awt.Color(255, 255, 255));
		     DeadlineField2.setText(prj[4]);
	     }
	 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeadlineLabel1 = new javax.swing.JLabel();
        DeadlineField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionArea = new javax.swing.JTextArea();
        NameProject = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NameLabel1 = new javax.swing.JLabel();
        OwnerField = new javax.swing.JTextField();
        OpenChatButton = new javax.swing.JButton();
        ComboBoxCard = new javax.swing.JComboBox<>();
        ShowCard = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ButtonNewCard = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ListMemberButton = new javax.swing.JButton();
        DeadlineLabel = new javax.swing.JLabel();
        DeadlineField = new javax.swing.JTextField();
        DeadlineField2 = new javax.swing.JTextField();
        DataCreatedLabel = new javax.swing.JLabel();

        DeadlineLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeadlineLabel1.setText("Deadline:");

        DeadlineField1.setEditable(false);
        DeadlineField1.setBackground(new java.awt.Color(255, 255, 255));
        DeadlineField1.setText("deadline");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Progetto:");

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLabel.setText("Name:");

        DescriptionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DescriptionLabel.setText("Description:");

        DescriptionArea.setEditable(false);
        DescriptionArea.setColumns(20);
        DescriptionArea.setRows(5);
        jScrollPane1.setViewportView(DescriptionArea);

        NameProject.setEditable(false);
        NameProject.setBackground(new java.awt.Color(255, 255, 255));
        NameProject.setText("Name");
        NameProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameProjectActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cards:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        NameLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameLabel1.setText("Owner:");

        OwnerField.setEditable(false);
        OwnerField.setBackground(new java.awt.Color(255, 255, 255));
        OwnerField.setText("Owner");
        OwnerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerFieldActionPerformed(evt);
            }
        });

        OpenChatButton.setText("Open");//chat
        OpenChatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenChatButtonActionPerformed(evt);
            }
        });

        ComboBoxCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TO DO", "IN PROGRESS", "TO BE REVISED", "DONE" }));
        ComboBoxCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCardActionPerformed(evt);
            }
        });

        ShowCard.setText("Show");
        ShowCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ShowCardActionPerformed(evt);
            }
        });
        
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Chat:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Delete Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProjectActionPerformed(evt);
            }
        });
        
        ButtonNewCard.setText("Create card");
        ButtonNewCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	ButtonNewCardActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Member:");

        ListMemberButton.setText("Open");
        ListMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMemberButtonActionPerformed(evt);
            }
        });

        DeadlineLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeadlineLabel.setText("Deadline:");

        DeadlineField.setEditable(false);
        DeadlineField.setBackground(new java.awt.Color(255, 255, 255));
        DeadlineField.setText("deadline");

        DeadlineField2.setEditable(false);
        DeadlineField2.setBackground(new java.awt.Color(255, 255, 255));

        DataCreatedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DataCreatedLabel.setText("Date created:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeadlineLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BackButton))
                            .addComponent(DataCreatedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DescriptionLabel)
                                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(NameProject)
                            .addComponent(DeadlineField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OwnerField)
                            .addComponent(DeadlineField2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OpenChatButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonNewCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ListMemberButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(ComboBoxCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17)
                                        .addComponent(ShowCard)
                                        .addGap(11, 11, 11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(40, 40, 40))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel1)
                    .addComponent(OwnerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowCard))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLabel)
                            .addComponent(NameProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescriptionLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DataCreatedLabel)
                            .addComponent(DeadlineField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeadlineField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeadlineLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonNewCard)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OpenChatButton)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ListMemberButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ButtonNewCardActionPerformed(java.awt.event.ActionEvent evt){
        GUIClientMain.NewCard(this.name);
    }
    
    private void ShowCardActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	int chosen = ComboBoxCard.getSelectedIndex();
    	
    	GUIClientMain.ShowCards(this.name, chosen);
    }
    
    private void DeleteProjectActionPerformed(java.awt.event.ActionEvent evt) {                                            
    	if(GUIClientMain.DeletePrj(this.name)) {
    		GUIClientMain.ShowProjects();
    	}
    	else{
    		JOptionPane.showMessageDialog(this, "You cannot delete the project if you have at least one card in a DONE list");
    	}
    }
    
    private void NameProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameProjectActionPerformed

    private void OwnerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OwnerFieldActionPerformed

    private void OpenChatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenChatButtonActionPerformed
    	GUIClientMain.ChatShow(this.name);
    }//GEN-LAST:event_OpenChatButtonActionPerformed

    private void ComboBoxCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCardActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
    	GUIClientMain.ShowProjects();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ListMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMemberButtonActionPerformed
        GUIClientMain.ShowMember(this.name);
    }//GEN-LAST:event_ListMemberButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton ButtonNewCard;
    private javax.swing.JComboBox<String> ComboBoxCard;
    private javax.swing.JLabel DataCreatedLabel;
    private javax.swing.JTextField DeadlineField;
    private javax.swing.JTextField DeadlineField1;
    private javax.swing.JTextField DeadlineField2;
    private javax.swing.JLabel DeadlineLabel;
    private javax.swing.JLabel DeadlineLabel1;
    private javax.swing.JTextArea DescriptionArea;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JButton ListMemberButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JTextField NameProject;
    private javax.swing.JButton OpenChatButton;
    private javax.swing.JTextField OwnerField;
    private javax.swing.JButton ShowCard;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
